### ISSUE TITLE
Including images

### ISSUE THREAD

**Issue by shurik179** [GeekyStudios/rFTC-wiki#14]
Anyone knows if Reddit flavor of markdown supports image inclusion?

**Comment by GeekyStudios** [comment]
As seen in [this](https://www.reddit.com/r/reddit.com/comments/6ewgt/reddit_markdown_primer_or_how_do_you_do_all_that/c03nik6/) post, the community agrees that Reddit will not implement images anytime in the future. Just link to a direct image if you want to. Make sure it's obvious that the link is an image.

**Comment by shurik179** [comment]
This is really disappointing. It is hard to imagine a wiki without inline images. 

Are we sure we want to build the wiki on Reddit? it creates a bunch of problems - for example,  links between wiki pages only become active after the content is published on Reddit (so they are not active on GitHub), inability to do inline images, and more. 

Why not do it in a real wiki and just put the link on reddit?  It is easy to find a hosting and install MediaWiki (e.g., I could offer our team's hosting). It would also make collaboration much faster - e.g. right now there are two conflicting pull requests for actobotics.md, waiting for merge; for a wiki, all editing is done in real time, so the problem would not arise.

**Comment by GeekyStudios** [comment]
@shurik179 Yeah, I might steer this project  to MediaWiki. Reddit really doesn't seem friendly to its wikis. In order to make a MediaWiki popular though, we'd have to get some nice SEO and marketing. I'll see if I could pitch it to my FIRST contacts.

For now, this Github is all we have.
