### ISSUE TITLE
Reorganization of the Wiki

### ISSUE THREAD

**Issue by Weznon** [GeekyStudios/rFTC-wiki#4]
As discussed by /u/shurik179 and I [here](https://www.reddit.com/r/FTC/comments/7gjn6c/im_encouraging_teams_to_contribute_to_rftcs_wiki/dqk0hgs/), we believe there should be a change in the organization. The proposal I have is two have 5 or 6 main folders/pages, based off of the main channels in the FTC discord, which I feel makes a fair bit of sense.

1. Programming
2. Building
3. Design
4. Notebook
5. Team Administration

The possible 6th folder is contributing to the wiki, where things like the header/footer and guidelines would go. This could also be kept on the git instead, though I like the idea of having it all on the wiki

I am on the fence whether there should be a folder specifically targeted at new teams, for the "starting a new team" style wiki pages. Might be another addition if there is enough material for it.

Of course, there would be more subpages/folders underneath these main folders.

I will be working on this on the [reorganize branch](https://github.com/Weznon/rFTC-wiki/tree/reorganize) of my fork; if anyone wants to help or has other ideas on how to organize please let me know.

This will be really annoying to merge later on, if we have lots of people working on other things and more files to shuffle around. It would be best if we decided on a system for this earlier than later.

**Comment by Weznon** [comment]
https://github.com/Weznon/rFTC-wiki/commit/2ea02836f4acce8d8520ebf7cce16d435593c464

Thats the initial reorganize I did, I wrote a comment explaining some choices I made

**Comment by GeekyStudios** [comment]
Looks good so far, Seems like it'll be easier to work with if the wiki gets bigger. I'm thinking of modifying the file tree on your README for you.

**Comment by shurik179** [comment]
I support Weznon's suggestion. Let us merge his changes into the master branch.

**Comment by GeekyStudios** [comment]
Will merge, There will be an issue posted up for all the inconsistencies created by it.

**Comment by shurik179** [comment]
Do you want to merge it to master instead of a different branch?

**Comment by Weznon** [comment]
What are some of the inconsistencies? I have time to work on ironing out them but I'm not sure what they are.

**Comment by GeekyStudios** [comment]
Links:
 - [building-systems](https://github.com/GeekyStudios/rFTC-wiki/blob/restructuring/building/building-systems/building-systems.md)
 - [REV-Robotics](https://github.com/GeekyStudios/rFTC-wiki/blob/restructuring/building/building-systems/t-slot-extrusions.md)

Would also like to change all file and folder names to either all caps or all lowercase:
 - newTeams to new-teams
 - building/commonBuildDesigns to building/common-build-designs or even common-designs
 - Actobotics to actobotics
 - Andymark to andymark
 - GoBilda to gobilda
 - MATRIX-Robotics to matrix-robotics
 - REV-Robotics to rev-robotics
 - TETRIX to tetrix
 - VEX-EDR to vex-edr
 - VEX-Pro to vex-pro

**Comment by GeekyStudios** [comment]
Actually, I'll go fix them right now. Then I'll merge to master.

**Comment by Weznon** [comment]
added landing pages aka an index for the main folders. will help with organization of the actual wiki on /r/ftc

https://github.com/GeekyStudios/rFTC-wiki/pull/10
