### ISSUE TITLE
Addition of REV Robotics to T-slot extrusions

### ISSUE THREAD

**Issue by GeekyStudios** [GeekyStudios/rFTC-wiki#5]
I recently merged an article on T-slot/8020 extrusions. It mentions several suppliers for T-slots but omits REV, which uses T-slots as their main building component. It would be appreciated if this was fixed. I'm personally working on the index pages.

**Comment by GeekyStudios** [comment]
Reopening the pull request.

**Comment by shurik179** [comment]
The section on T-slot extrusions says "T-slot extrusions are also used by a new robot building system, Rev Robotics, described in a separate section. They use 15mm square extrusions."
We should convert it to an active link, but otherwise, I think it is OK.

**Comment by GeekyStudios** [comment]
Apparently, I can't read. I'm adding the link in a single commit. Also going to rename the file to simply t-slot-extrusions.md.
